### ISSUE TITLE
Please update your code to newest chromaprint 1.4

### ISSUE THREAD

**Issue by PeterCodar** [wo80/AcoustID.NET#3]
The original author of AcoustID has updated his chromaprint:
https://oxygene.sk/2016/12/chromaprint-1-4-released/

> This change is also reflected in the fpcalc utility, which can now work on streams. In fact, the fpcalc utility has been completely rewritten. It now also supports JSON output for easier integration, since you can find JSON parser in the standard library of almost every new programing language.

Could you please have a look and update your code (if necessary)?

**Comment by 0xcaff** [comment]
These all seem to be updates around `fpcalc`, the command line utility not the acoustid chromaprint library or algorithms.

**Comment by wo80** [comment]
I took a look at the changes to the chromaprint codebase back then and most of them we're related to using new features of the C++ standard.

I'll close this one, but feel free to re-open, if you think that there are new features or changes to the algorithms.
