### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Clancey** [wo80/AcoustID.NET#4]
You reference https://bitbucket.org/acoustid/chromaprint/src/3f07ceef8438058d14a1d479009cb66779cf3594/LICENSE.md?at=master&fileviewer=file-view-default for adding the LGPL license. 

However they mention the only reason for LGPL is by referencing FFMPEG, and once that is removed it will be MIT. However this lib does not rely on FFMPEG.  Is there a reason it is LGPL instead of MIT?

**Comment by wo80** [comment]
I'd be glad to publish this as MIT, but [Resampler.cs](https://github.com/wo80/AcoustID.NET/blob/master/AcoustID/Audio/Resampler.cs) is a direct translation of the avresample code (see [chromaprint/src/avresample/resample2.c](https://bitbucket.org/acoustid/chromaprint/src/3f07ceef8438058d14a1d479009cb66779cf3594/src/avresample/resample2.c?at=master)).

So, as a whole, this library has to be considered LGPL.

I might add the same note about MIT like Lukas did, so lets leave this issue open for now.
