### ISSUE TITLE
Using AcoustID.NET

### ISSUE THREAD

**Issue by shanecody32** [wo80/AcoustID.NET#7]
I am trying to use AcoustID.NET for a project but the examples that was provided to a different issue does not work.

When I try to use the following, context does not have a Consumer property:
```
var decoder = new NAudioDecoder(filename);
var context = new ChromaContext();

context.Start(decoder.SampleRate, decoder.Channels);
decoder.Decode(context.Consumer, 120);
context.Finish();

var fp = context.GetFingerprint();

```

**Comment by wo80** [comment]
Try `decoder.Decode(context, 120)`.

**Comment by wo80** [comment]
Feel free to re-open if you're still having issues.
