### ISSUE TITLE
System.Xml.XmlException when running LookupService.GetAsync()

### ISSUE THREAD

**Issue by nlogozzo** [wo80/AcoustID.NET#9]
`UnhandledException - unhandled exception: System.Xml.XmlException: There are multiple root elements. Line 2, position 2`

**Comment by wo80** [comment]
What was the actual HTTP request, what was the XML response? Do you have a stack trace?

`There are multiple root elements` sounds like AcoustID is returning badly formatted XML...

**Comment by wo80** [comment]
Closing this one. Feel free to re-open, but please be a bit more verbose about what you actually expect...
